### ISSUE TITLE
GRUB fails to build with grub-extras package

### ISSUE THREAD

**Issue by dustinwinski** [a1ive/grub-extras#1]
Hello a1ive,

I'm posting an issue here because I checked your website for an email and couldn't find one and nor does GitHub have a messaging feature. I know this isn't the best place for one to ask for _help_.

I followed the instructions in this repo's README, but the build fails at trying to build BITS. Funny enough, that is exactly what I'm after, as well.  I'm trying to build BITS with the latest stable version of GRUB. 

My questions are:

Do I need to use your "grub" repo in order for these extras to work?
If so, what changes have you made from the mainline GRUB?

Do you have any more verbose instructions?

What versions of make and GCC do you use?
I'm using Make 4.2 and GCC 9.2.

**Comment by a1ive** [comment]
> Do I need to use your "grub" repo in order for these extras to work?

Yes.

> If so, what changes have you made from the mainline GRUB?

Some patches for BITS are stolen from https://github.com/3mdeb/grub and https://github.com/3mdeb/bits
BITS modules in this repo are buggy, and smp module doesn't work under x86_64-efi. 

> Do you have any more verbose instructions?
> What versions of make and GCC do you use?

Make 4.2 & GCC 9.2
```
cd grub
export GRUB_CONTRIB=$HOME/grub-extras
./bootstrap
./configure --prefix=$HOME/PKG --target=i386 --with-platform=pc
make
```

**Comment by dustinwinski** [comment]
Could I delete/remove the smp directory? I did some looking and it seems that smp refers to symmetric multitasking capability. 

Are there other additions inside your fork that depend on this package?

**Comment by a1ive** [comment]
I've already disabled it for x86_64-efi.
see https://github.com/a1ive/grub-extras/blob/3bad299b8e75ec7febda5b4f1ebe72066a8e7cbf/bits/python/config.c#L154

**Comment by dustinwinski** [comment]
Please accept my ignorance as I'm not a C programmer and all these utilities like Make and what not are new to me...

Are you saying I can attempt a build for x86 EFI and not have to worry about that module?

For example, by doing the following:
`cd grub`
`export GRUB_CONTRIB=$HOME/grub-extras`
`./bootstrap`
`./configure --prefix=$HOME/PKG --target=x86_64 --with-platform=efi`
`make`

I notice this fork is structured extremely differently than the official BIOSBITS repo. 
I also failed at building their latest stable release despite following the instructions.
Are your changes an attempt to make building BITS easier? It does seem that way.

**Comment by a1ive** [comment]
BITS contains two parts : grub2 module and python lib.
This repo only contains grub2 module.You could copy python libs from https://github.com/3mdeb/bits/tree/bits_grub_payload/python
Since x86_64-efi build don't have smp module, you should modify the python code.
https://github.com/a1ive/grub2-filemanager/tree/9029e93c44359bb104d4301796b4657595abbe07/boot/python

**Comment by dustinwinski** [comment]
Thank you for your help. I'm going to go ahead and close this issue.
